// Package fsm implements ChronicleDB's deterministic Apply boundary
// (docs/architecture.md §5, ADR-0007): the sole function that turns an
// ordered, durable command history into database state. Apply depends
// only on the command's own fields plus the FSM's own prior committed
// state — never on wall-clock time, randomness, environment queries,
// filesystem access, network calls, or unordered map iteration
// (docs/invariants.md DETERMINISM BOUNDARY). This package has no I/O:
// internal/txn owns the WAL and decides what gets durably appended;
// internal/fsm only ever sees command bytes/structs already decided to
// be part of the ordered history, and returns a deterministic result.
package fsm

import (
	"encoding/binary"
	"fmt"

	"github.com/SamudralaAjaykumarrr/chronicledb/internal/mvcc"
)

// RequestID is a client-supplied, opaque idempotency token attached to
// a mutating request (docs/architecture.md §3, ADR-0006). ChronicleDB
// never interprets its bytes — only compares them for equality — so a
// plain string (Go strings are immutable byte sequences) is a
// sufficient representation; it is never generated by the server.
type RequestID string

// commitTxnCommandVersion is the format version of the CommitTxn
// command payload this file encodes/decodes. It is a distinct version
// byte from internal/wal's own per-frame format version (docs/wal.md
// §3): the WAL frame's version governs frame layout, while this one
// governs the layout of the opaque command bytes carried inside a
// RecordTypeLogEntry payload.
//
// Version 2 adds the RequestID field required by Phase 3
// (docs/roadmap.md); version 1 (Phase 2, internal/txn's now-removed
// commitTxnCommand) never carried one. No Phase-1/2 production data
// exists to migrate, so decode simply rejects version 1 rather than
// carrying a compatibility shim (see docs/transactions.md §9/§10).
const commitTxnCommandVersion uint8 = 2

// CommitTxnCommand is the in-memory form of the single deterministic
// command a COMMIT submits (docs/transactions.md §3):
//
//	CommitTxn(RequestID, TxnID, StartSeq, Mutations...)
//
// It is self-contained: internal/fsm.Apply computes the identical
// outcome from cmd's own fields plus its own prior committed state,
// regardless of which node or replica evaluates it (docs/transactions.md
// §3). TxnID is carried as a raw uint64 rather than internal/txn.TxnID
// to keep internal/fsm free of any dependency on internal/txn
// (docs/architecture.md §5 dependency rules: fsm depends downward on
// mvcc, never upward on the package that constructs commands for it).
type CommitTxnCommand struct {
	RequestID RequestID
	TxnID     uint64
	StartSeq  uint64
	Mutations []mvcc.Mutation
}

// EncodeCommitTxn serializes cmd into a CommitTxn command payload
// suitable for durable storage (e.g. as an internal/wal
// RecordTypeLogEntry payload). Encoding never depends on map iteration
// order: cmd.Mutations is an explicit, already-ordered slice (callers
// are responsible for fixing that order once, at command-construction
// time — see internal/txn.Txn.order).
//
// Layout:
//
//	version(1B) requestIDLen(4B) requestID(requestIDLen)
//	  txnID(8B) startSeq(8B) numMutations(4B)
//	  per mutation: keyLen(4B) key(keyLen) tombstone(1B) [valLen(4B) value(valLen)]
//
// (valLen/value are present only when tombstone == 0.)
func EncodeCommitTxn(cmd CommitTxnCommand) []byte {
	body := encodeCommitBody(cmd)
	size := 1 + 4 + len(cmd.RequestID) + len(body)
	buf := make([]byte, size)
	off := 0
	buf[off] = commitTxnCommandVersion
	off++
	binary.BigEndian.PutUint32(buf[off:], uint32(len(cmd.RequestID)))
	off += 4
	off += copy(buf[off:], cmd.RequestID)
	copy(buf[off:], body)
	return buf
}

// encodeCommitBody encodes the portion of cmd that determines its
// deterministic outcome (TxnID, StartSeq, Mutations) — everything
// except RequestID itself. This is also used as the durable
// fingerprint of "what this RequestID was originally submitted with"
// (see fingerprint in fsm.go): two submissions under the same
// RequestID are the same logical request only if this body is
// byte-identical.
func encodeCommitBody(cmd CommitTxnCommand) []byte {
	size := 8 + 8 + 4
	for _, m := range cmd.Mutations {
		size += 4 + len(m.Key) + 1
		if !m.Tombstone {
			size += 4 + len(m.Value)
		}
	}
	buf := make([]byte, size)
	off := 0
	binary.BigEndian.PutUint64(buf[off:], cmd.TxnID)
	off += 8
	binary.BigEndian.PutUint64(buf[off:], cmd.StartSeq)
	off += 8
	binary.BigEndian.PutUint32(buf[off:], uint32(len(cmd.Mutations)))
	off += 4
	for _, m := range cmd.Mutations {
		binary.BigEndian.PutUint32(buf[off:], uint32(len(m.Key)))
		off += 4
		off += copy(buf[off:], m.Key)
		if m.Tombstone {
			buf[off] = 1
		} else {
			buf[off] = 0
		}
		off++
		if !m.Tombstone {
			binary.BigEndian.PutUint32(buf[off:], uint32(len(m.Value)))
			off += 4
			off += copy(buf[off:], m.Value)
		}
	}
	return buf
}

// DecodeCommitTxn parses a CommitTxn command payload. It never trusts
// a length or count field beyond the bytes actually remaining in b,
// mirroring internal/wal's decodeFrameBytes bounded-decoding
// discipline (docs/failure-model.md §6, "bounded request sizes /
// bounded allocations"): it returns an error, never panics, on any
// malformed or truncated input, and every allocation it makes is
// bounded by bytes already known to be present in b, not by an
// unvalidated count field.
func DecodeCommitTxn(b []byte) (CommitTxnCommand, error) {
	var cmd CommitTxnCommand
	const fixedHeaderSize = 1 + 4
	if len(b) < fixedHeaderSize {
		return cmd, fmt.Errorf("%w: payload too short (%d bytes, need at least %d)", ErrMalformedCommand, len(b), fixedHeaderSize)
	}
	off := 0
	version := b[off]
	off++
	if version != commitTxnCommandVersion {
		return cmd, fmt.Errorf("%w: command version %d, expected %d", ErrUnsupportedCommandVersion, version, commitTxnCommandVersion)
	}

	reqIDLen := binary.BigEndian.Uint32(b[off:])
	off += 4
	if int64(reqIDLen) > int64(len(b)-off) {
		return cmd, fmt.Errorf("%w: truncated RequestID (declared %d bytes, %d remain)", ErrMalformedCommand, reqIDLen, len(b)-off)
	}
	cmd.RequestID = RequestID(b[off : off+int(reqIDLen)])
	off += int(reqIDLen)

	const bodyFixedHeaderSize = 8 + 8 + 4
	if len(b)-off < bodyFixedHeaderSize {
		return cmd, fmt.Errorf("%w: truncated body (%d bytes remain, need at least %d)", ErrMalformedCommand, len(b)-off, bodyFixedHeaderSize)
	}
	cmd.TxnID = binary.BigEndian.Uint64(b[off:])
	off += 8
	cmd.StartSeq = binary.BigEndian.Uint64(b[off:])
	off += 8
	numMutations := binary.BigEndian.Uint32(b[off:])
	off += 4

	// Bound numMutations against the bytes actually remaining, not an
	// arbitrary constant: the smallest possible encoded mutation is 5
	// bytes (a zero-length key's 4-byte length prefix plus a 1-byte
	// tombstone flag), so no more than remaining/5 mutations can
	// legitimately be present. This prevents a small, corrupt or
	// adversarial payload from declaring an enormous mutation count and
	// forcing a large pre-allocation before any of its content is
	// validated.
	remaining := len(b) - off
	const minEncodedMutationSize = 4 + 1
	if numMutations > uint32(remaining/minEncodedMutationSize) {
		return cmd, fmt.Errorf("%w: declares %d mutations but only %d bytes remain", ErrMalformedCommand, numMutations, remaining)
	}

	mutations := make([]mvcc.Mutation, 0, numMutations)
	for i := uint32(0); i < numMutations; i++ {
		if len(b)-off < 4 {
			return cmd, fmt.Errorf("%w: truncated mutation %d (key length)", ErrMalformedCommand, i)
		}
		keyLen := binary.BigEndian.Uint32(b[off:])
		off += 4
		if int64(keyLen) > int64(len(b)-off) {
			return cmd, fmt.Errorf("%w: truncated mutation %d (key: declared %d bytes, %d remain)", ErrMalformedCommand, i, keyLen, len(b)-off)
		}
		key := string(b[off : off+int(keyLen)])
		off += int(keyLen)

		if len(b)-off < 1 {
			return cmd, fmt.Errorf("%w: truncated mutation %d (tombstone flag)", ErrMalformedCommand, i)
		}
		tombstone := b[off] != 0
		off++

		var value []byte
		if !tombstone {
			if len(b)-off < 4 {
				return cmd, fmt.Errorf("%w: truncated mutation %d (value length)", ErrMalformedCommand, i)
			}
			valLen := binary.BigEndian.Uint32(b[off:])
			off += 4
			if int64(valLen) > int64(len(b)-off) {
				return cmd, fmt.Errorf("%w: truncated mutation %d (value: declared %d bytes, %d remain)", ErrMalformedCommand, i, valLen, len(b)-off)
			}
			value = make([]byte, valLen)
			copy(value, b[off:off+int(valLen)])
			off += int(valLen)
		}
		mutations = append(mutations, mvcc.Mutation{Key: key, Value: value, Tombstone: tombstone})
	}
	if off != len(b) {
		return cmd, fmt.Errorf("%w: %d trailing bytes after decoding %d mutations", ErrMalformedCommand, len(b)-off, numMutations)
	}
	cmd.Mutations = mutations
	return cmd, nil
}
